// Auto-generated by Supabase MCP — do not edit manually
// Regenerate with: supabase gen types typescript --project-id tqkvifmyppithjlwrzkl

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      clicks: {
        Row: {
          id: string
          click_id: string
          product_id: string
          merchant: string
          destination_url: string | null
          source_page: string | null
          referrer: string | null
          device: string | null
          clicked_at: string
        }
        Insert: {
          id?: string
          click_id: string
          product_id: string
          merchant: string
          destination_url?: string | null
          source_page?: string | null
          referrer?: string | null
          device?: string | null
          clicked_at?: string
        }
        Update: {
          id?: string
          click_id?: string
          product_id?: string
          merchant?: string
          destination_url?: string | null
          source_page?: string | null
          referrer?: string | null
          device?: string | null
          clicked_at?: string
        }
        Relationships: []
      }
      conversions: {
        Row: {
          id: string
          click_id: string | null
          order_id: string
          amount: number
          commission: number
          merchant: string | null
          status: string
          converted_at: string
        }
        Insert: {
          id?: string
          click_id?: string | null
          order_id: string
          amount?: number
          commission?: number
          merchant?: string | null
          status?: string
          converted_at?: string
        }
        Update: {
          id?: string
          click_id?: string | null
          order_id?: string
          amount?: number
          commission?: number
          merchant?: string | null
          status?: string
          converted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversions_click_id_fkey"
            columns: ["click_id"]
            isOneToOne: false
            referencedRelation: "clicks"
            referencedColumns: ["click_id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Convenience helpers
export type Click = Database['public']['Tables']['clicks']['Row']
export type ClickInsert = Database['public']['Tables']['clicks']['Insert']
export type Conversion = Database['public']['Tables']['conversions']['Row']
export type ConversionInsert = Database['public']['Tables']['conversions']['Insert']
